# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: danilo
  password: 

development:
  <<: *default
  database: system_development


test:
  <<: *default
  database: system_test

production:
  <<: *default
  database: system_production
  username: system
  password: <%= ENV['SYSTEM_DATABASE_PASSWORD'] %>
